### ISSUE TITLE
[FR]: Focus filename after creating a note (like default Obsidian)

### ISSUE THREAD

**Issue by redactedscribe** [Lisandra-dev/obsidian-create-note-in-folder#13]
Just after creating a note, the cursor is automatically positioned in the body of the note instead of its inline title / tab title bar. Ideally we could create a note and immediately type its title (filename), instead of having to click it first then type. This happens when a folder is using Templater template, or none at all.

Thanks.

**Comment by Mara-Li** [comment]
I will love to do that, but can't find anything in the API that could let me to do this. I leave this request as standby until I found a proper solution.

**Comment by redactedscribe** [comment]
Hello @Lisandra-dev, is it possible for you to take a [look at this issue](https://github.com/snezhig/obsidian-front-matter-title/issues/193)? It seems to be a compatibility issue with another plugin known as [Front Matter Title](https://github.com/snezhig/obsidian-front-matter-title) being able to focus the title when both plugins are enabled. Maybe you can make sense of the latest comment regarding your code. Thank you.

**Comment by Mara-Li** [comment]
(joking) Yeay, a way to fly my finals (joking)

I will take a look, thanks for the investigation !

**Comment by redactedscribe** [comment]
It seems to work. Thank you! The only other thing is that if the template is long in length, it's possible that the title cannot be seen because the page scrolls to the bottom for some reason. But, the title _is_ highlighted and so I can start typing and it'll scroll up to see the inline title. It might be a side effect of another plugin so I don't think you need to try and fix that now. If I find out more, I'll let you know.

Thank you again!

**Comment by Mara-Li** [comment]
It should scroll now!

**Comment by redactedscribe** [comment]
> It should scroll now!

I didn't notice any change with the new version, but as I said, if I start typing, it scrolls up so I can see the inline title, so it's functional enough in this state. Could be something else.

It does work when I remove Templater's `<% tp.file.cursor() %>` from my template. That was probably the issue, the note is now always scrolled to the top. I think it might be a Templater bug.

---

Secondly, I think there's a bug when a Templater template includes `<% tp.file.rename("New note") -%>`: The inline title is focused after note creation, and can be typed into, but inserted text does not overwrite "New note" and is instead prepended to it ("New note" isn't pre-selected). Removing `<% tp.file.rename("New note") -%>` and creating the note now has "New note" selected and ready to be typed over.

The inline title is always pre-selected if Create Note in Folder's folder specific settings is also set to "New note" for its note name. Then it will match the Templater code `<% tp.file.rename("New note") -%>` and the inline title will be selected. If folder settings note name differs to `<% tp.file.rename("...") -%>` then this bug occurs.

**Comment by redactedscribe** [comment]
@Mara-Li Hello again. Thanks for your continued development of this plugin, however it appears that the latest release re-introduced this issue again. After creating a note, the cursor is on line 1 instead of in the inline title / tab title bar.

**Comment by Mara-Li** [comment]
A simple refractor could do this?
Will fix this tomorrow, sorry for the inconvenience!

**Comment by redactedscribe** [comment]
It appears so. Hopefully the solution will be simple.

**Comment by Mara-Li** [comment]
Yeah, no worry, I know what cause the error ^^

**Comment by Mara-Li** [comment]
Should be fixed again

**Comment by redactedscribe** [comment]
Yep, it's fixed. Thanks @Mara-Li!
