### ISSUE TITLE
Create note with text selection

### ISSUE THREAD

**Issue by lifehaschanged** [Lisandra-dev/obsidian-create-note-in-folder#16]
Hi @Lisandra-dev 

Thank you for this plugin.
I am not a programmer myself (apologize) but want to use your plugin for a specific need.

I want to right click a text selection in a note and create a new note with it in a specific path.
I then want to create commands with many different paths for the right click menu with your plugin.

The new created note has then title/content from the text selection of the previous note inside.

**Comment by Mara-Li** [comment]
It could be possible using the plugin Templater.

**Comment by lifehaschanged** [comment]
Thank you for the answer, but I can't code 😥.
But maybe you want to implement it as a core feature in your plugin, someday?

**Comment by Mara-Li** [comment]
Nan, it's outside the scope of the plugin.
You don't need to know how to code (and at last, it's not late to start!). And you can ask help on the forum, discord etc.

**Comment by lifehaschanged** [comment]
If you could provide me a templater script for this I'll be happy (:

**Comment by lifehaschanged** [comment]
Here is a song as a thank you: 
https://www.youtube.com/watch?v=OfTetvP9p5Q
