### ISSUE TITLE
How to create a file named only by date

### ISSUE THREAD

**Issue by DZL1943** [Lisandra-dev/obsidian-create-note-in-folder#17]
i tried to set the filename empty and set a date template, but it doesn't work.

**Comment by Mara-Li** [comment]
Hello.
![image](https://github.com/Mara-Li/obsidian-create-note-in-folder/assets/30244939/c4ac4915-184c-4e4e-9595-c9737b6f87a2)

**Comment by DZL1943** [comment]
I found the reason. It needs to be reloaded to take effect.

**Comment by Mara-Li** [comment]
What do you mean ? When it needs to be reloaded?
Normally, things should works out of the box, unless for templater that needs to be enabled in parallel

**Comment by DZL1943** [comment]
> What do you mean ? When it needs to be reloaded?
> Normally, things should works out of the box, unless for templater that needs to be enabled in parallel

For example, after you change the date format and commit, it will not take effect, but will still be displayed in the last named format, unless you restart obsidian or the plugin
