### ISSUE TITLE
[Bug]: Templater code flashes for a split second on new note creation

### ISSUE THREAD

**Issue by churnish** [Lisandra-dev/obsidian-create-note-in-folder#19]
### Issue validation

- [X] I checked the issue to prevent duplicate
- [X] I checked my configurations files and the documentation

### Describe the bug

When I create a new note w/ a *Templater* template attached below, its source code flashes for a second before being applied. This only happens when I use *Create Note in Folder*. This doesn't happen when the template is applied w/ *Templater* only, without using *Create Note in Folder*. Everything functions fine, the problem is purely visual: it's unsightly. I just wish the source code didn't flash like this 😢

Note: to circumvent this, I also attempted to use [QuickAdd](https://github.com/chhoumann/quickadd) instead, and ran into the same problem: the source code flashes just the same when using it! But given that that plugin has hundreds of open (and more pressing) GitHub issues, I don't think they will ever get around to fixing this...

### How to reproduce ?

1. Create command w/ the configuration below:

<img width="1152" alt="Screen Shot 2024-10-31 at 13 36 59" src="https://github.com/user-attachments/assets/70317bad-6452-4864-a495-eaca3d7d90f8">

<br>

2. Create new note w/ *Create Note in Folder* command:

https://github.com/user-attachments/assets/f4b61824-1aaf-4b6b-af1f-f7808ed06410

### Minimal Reproducible Example

Templater template:
```
---
created: <% moment(tp.file.creation_date()).format("YYYY.MM.DD HH:mm") %>
modified: <% moment().format("YYYY.MM.DD HH:mm") %>
tags: []
---
```

### Configuration

```JSON
{
  "folder": [
    {
      "path": "~Inbox 📥",
      "commandName": "Create Inbox Note in New Tab",
      "template": {
        "type": "none",
        "format": "~Inbox 📥",
        "position": "append",
        "separator": "",
        "increment": true
      },
      "fileName": "Untitled",
      "opening": "newTab",
      "focused": true,
      "splitDefault": "horizontal",
      "alreadyExistOpening": {
        "opening": "newTab",
        "splitDefault": "horizontal",
        "focused": true
      },
      "fileMenu": false,
      "templater": "一Templates/x.New-Note-Template.md"
    },
    {
      "path": "~Inbox 📥",
      "commandName": "Create Inbox Note in Same Tab",
      "template": {
        "type": "none",
        "format": "",
        "position": "append",
        "separator": "",
        "increment": true
      },
      "fileName": "Untitled",
      "opening": "current",
      "focused": true,
      "splitDefault": "horizontal",
      "alreadyExistOpening": {
        "opening": "newTab",
        "splitDefault": "horizontal",
        "focused": true
      },
      "fileMenu": false,
      "templater": "一Templates/x.New-Note-Template.md"
    },
    {
      "path": "~Inbox 📥",
      "commandName": "Create Inbox Note to The Right",
      "template": {
        "type": "none",
        "format": "",
        "position": "append",
        "separator": "",
        "increment": true
      },
      "fileName": "Untitled",
      "opening": "split",
      "focused": true,
      "splitDefault": "horizontal",
      "alreadyExistOpening": {
        "opening": "newTab",
        "splitDefault": "horizontal",
        "focused": true
      },
      "fileMenu": false,
      "templater": "一Templates/x.New-Note-Template.md"
    }
  ],
  "customVariables": [],
  "timeOutForInlineTitle": 50,
  "enableAllFolder": false
}
```

### OS

IOS, MacOS

### Obsidian information

```bash session
SYSTEM INFO:
	Obsidian version: v1.7.4
	Installer version: v1.7.4
	Operating system: Darwin Kernel Version 20.6.0: Thu Jul  6 22:12:47 PDT 2023; root:xnu-7195.141.49.702.12~1/RELEASE_X86_64 20.6.0
```

### Plugin version

1.12.2

**Comment by Mara-Li** [comment]
I think it's not fixable, as it the normal functionnement of Templater. To explain how Templater is used:
- The note is created with the template
- After the creation, templater is run 

The flash you see is the "run templater" command.

The flash should be present even if you use only templater and create a file from a template (i think?)

**Comment by churnish** [comment]
I don't observe flashing when using *Templater* only. Here, the same template is automatically applied on new note creation, and then manually:


https://github.com/user-attachments/assets/2df9487d-f504-47d3-95d8-e7a359051aa3

**Comment by Mara-Li** [comment]
Okay, I should investigate using templater API. I think my methods are the same as QuickAdd, as we "call" the templater as a command and not using Templater API internally.

**Comment by churnish** [comment]
Thanks so much for looking into this, and taking such swift action! 🥰
