### ISSUE TITLE
[Bug]: Incrementing New Notes in the Main Vault Folder doesn't seem to work

### ISSUE THREAD

**Issue by Cr8zyIvan** [Lisandra-dev/obsidian-create-note-in-folder#3]
"Create Note in Folder" doesn't seem to Increment New Notes if the Current Name already exists, when the set Folder is the Main Vault Folder ("/").

Essentially what I'm trying to do is:
Have a Hotkey for:
- Create a New Note in Main Vault Directory (with the "Create Note in Folder" Plugin and setting the Folder to "/" - Hotkey: Ctrl + N)
- Create a New Note in Current Folder (the Folder in Which the Current Note is Open - with Obsidian's native Hotkey "Create New Note" and setting it to "Create New Note in Current Folder" - Hotkey: Ctrl + Shift + N)

"Create Note in Folder" works well in every other Folder I've tried it. When creating a New Note in "/" however, the first note gets created (Untitled), and when I press the Hotkey a second time (which I've made sure there were no conflicts), just nothing happens afterwards. In other Folders "Untitled 1", "Untitled 2", etc. are created.

Perhaps this is a bug?

**Comment by Mara-Li** [comment]
Thanks, I will investigate!
