### ISSUE TITLE
Bug: If folder is added, New Note Quick Switcher stops working

### ISSUE THREAD

**Issue by redactedscribe** [Lisandra-dev/obsidian-create-note-in-folder#7]
Thanks for the quick switcher feature, it's much appreciated. There's a bug however:

In the plugin's options, "Add folder" and then define its folder path, existing or not (I tried `{{current}}` in an attempt to figure out how to use it -- I'm still not sure how -- I also tried `test` which doesn't exist, and `/` which of course does). After this, pressing the hotkey for the plugin's quick switcher no longer works (I re-assigned <kbd>Ctrl</kbd>+<kbd>N</kbd>). It can no longer be see in the Hotkeys list either. The only option is to disable and re-enable the plugin.

Thanks.

**Comment by Mara-Li** [comment]
Strange, will check this out!

For {{current}}, just set "{{current}}" in the path. You could also set `something/{{current}}/something` (normally, I must test it more), and if a file is opened, you can find the command and use it. It will create the `something/thefolderofthefile/something` for example.

**Comment by Mara-Li** [comment]
Oh god, I know what cause this bug, i'm stupid!

**Comment by redactedscribe** [comment]
Thanks for the fix, but it unfortunately appears to still be broken. Maybe you can check if adding a new folder is causing the plugin's two quick switcher options in the Command Palette to still disappear?

> For {{current}}, just set "{{current}}" in the path. You could also set something/{{current}}/something (normally, I must test it more), and if a file is opened, you can find the command and use it. It will create the something/thefolderofthefile/something for example.

Once it's fixed, I can try using `{{current}}`.

**Comment by Mara-Li** [comment]
Bruh, ty, will check this out.
It was a little typo 🤦

**Comment by redactedscribe** [comment]
> Once it's fixed, I can try using `{{current}}`.

Just to confirm, `{{current}}` works now 🙂
