### ISSUE TITLE
FR: Allow quick switcher to choose any folder

### ISSUE THREAD

**Issue by redactedscribe** [Lisandra-dev/obsidian-create-note-in-folder#8]
For example, after opening the plugin's create note in folder quick switcher, first list the defined folders, a dividing line, and then list all other existing folders in the vault below (minus the defined ones above).

The plugin's options should then introduce a new folder in the list called "Default" or "Fallback" which can be customised (except its name) and would be used for all other folders that haven't been specifically added as a folder to the list.

This would allow: Create note in folder quick switcher hotkey (e.g. <kbd>Ctrl</kbd>+<kbd>N</kbd>) > search defined folders or any other > click/enter to create note using the folder's specific settings (or the default settings if folder hasn't got specific settings).

No need to create notes in folders via the Files tab/sidebar any more, unless you don't want to trigger the default folder settings. The default folder settings feature would be optional by simply not customising its settings.

Thanks.

**Comment by Mara-Li** [comment]
For the divine line, I don't know if I could add CSS in the fuzzysearch, but will check it out! If I can't, I think I will add a option that will open another modal with all folders. Like "Other folder" click ⇒ modal 2 ⇒ List all folder. 

For the default/Fallback, why don't you use directly templater ? 

I can introduce it without problem, but I want to know <3

**Comment by redactedscribe** [comment]
> For the default/Fallback, why don't you use directly templater ?

Good point. I was trying to use your plugin as a full replacement of Templater's Folder Templates, but if I define `/` and a Templater template as one of its Folder Templates, that should work nicely as the default/fallback I suggested. If there's a problem, I'll let you know.

**Comment by redactedscribe** [comment]
> For the divine line, I don't know if I could add CSS in the fuzzysearch, but will check it out! If I can't, I think I will add a option that will open another modal with all folders. Like "Other folder" click ⇒ modal 2 ⇒ List all folder.

Ideally all folders would be listed on the same quick switcher "page" so that they can all be searched for immediately. If there isn't a way to add a dividing line, maybe there's a way to pin them to the top. Obsidian native allows pinning certain commands to the top of the Command Palette, maybe something similar is possible for the quick switcher?

**Comment by Mara-Li** [comment]
It must be too much difficult for me x)

The problem is that I don't want to add to much in the list if you have a lot of folder. I will try some configuration

**Comment by redactedscribe** [comment]
>It must be too much difficult for me x) 

I'm sure you can figure something out.

> The problem is that I don't want to add to much in the list if you have a lot of folder. I will try some configuration

It's up to you, but the quick switcher will show a scrollbar if there are a lot of folders.

**Comment by redactedscribe** [comment]
Thanks for the feature @Lisandra-dev.

Bug:

- **Edit:** Any folder quick switcher is filtering out all of the user-added folders. Meaning, since I have "Root" added for "/", the any quick switcher isn't listing `/` as an option, when it should. The folders in the Any folder quick switcher should use the original folder names, not the ones given by the user in the options: `/`, not the label "Root" which I gave it. The non-any folder quick switcher correctly filters out all other folders below the dividing line (nice that you figured out how to do it).

Feedback:

- It could also list `{{current}}` so that you can search for that instead of having to know which folder you're in.

**Comment by Mara-Li** [comment]
Thanks for the feedback! I will update it ASAP :)
