### ISSUE TITLE
Ability to rearrange user-defined folders

### ISSUE THREAD

**Issue by redactedscribe** [Lisandra-dev/obsidian-create-note-in-folder#9]
It would be nice if folders that the user has defined could be manually sorted. For example, if I want my most common folder that I create something in to be the first option for the sake of convenience and speed, I need to move all the other folder definitions down by one. Rearranging folders would help.

Thanks.

**Comment by Mara-Li** [comment]
Will do it… Later. I must eat instead of coding !
(I love coding, I have the tendance of hyperfocusing it, so I forgot to eat :'D)

**Comment by redactedscribe** [comment]
Make sure to eat more because I have another (small) FR. Thanks for the implementation!
